#!/usr/bin/env bash
#
# Pre-launch repository audit.
#
# Reports only — it never edits or deletes anything. Run it before a release:
#
#   npm run audit:repo
#
# Exit code is 1 if any BLOCKER is found, so CI can gate on it.

set -uo pipefail
cd "$(dirname "$0")/.."

RED=$'\033[31m'; YEL=$'\033[33m'; GRN=$'\033[32m'; DIM=$'\033[2m'; OFF=$'\033[0m'
blockers=0

section() { printf '\n%s── %s%s\n' "$DIM" "$1" "$OFF"; }
ok()      { printf '  %s✓%s %s\n' "$GRN" "$OFF" "$1"; }
warn()    { printf '  %s!%s %s\n' "$YEL" "$OFF" "$1"; }
block()   { printf '  %s✗%s %s\n' "$RED" "$OFF" "$1"; blockers=$((blockers + 1)); }

# Count matches, tolerating "no matches" without tripping set -e.
count() { grep -rniE "$1" src public *.ts *.json *.md 2>/dev/null | grep -vc '^$' || true; }

section "Tooling attribution"
tools=$(count 'claude|anthropic|chatgpt|openai|copilot|codeium|cursor\.so|generated by (an )?ai|ai-generated')
if [ "${tools:-0}" -eq 0 ]; then
  ok "no assistant or generator names in source"
else
  warn "$tools reference(s) to an assistant or generator — review before publishing"
  grep -rniE 'claude|anthropic|chatgpt|openai|copilot|codeium|generated by (an )?ai' src public *.ts *.md 2>/dev/null | head -10
fi

section "Delivery leftovers"
leftovers=0
for f in APPLY.txt SECURITY-PATCH.txt NOTES.txt notes.md; do
  [ -f "$f" ] && { warn "$f is a hand-off note, not part of the product — delete it"; leftovers=1; }
done
[ "$leftovers" -eq 0 ] && ok "no hand-off notes in the repo root"

section "Unfinished content"
ph=$(grep -rn 'PLACEHOLDER\|PLATZHALTER' src/data 2>/dev/null | wc -l | tr -d ' ')
if [ "${ph:-0}" -eq 0 ]; then
  ok "no placeholders left in content or legal files"
else
  block "$ph placeholder(s) still visible to visitors — fill before launch"
  grep -rno 'PLACEHOLDER[^]"]*' src/data 2>/dev/null | head -8
fi

lorem=$(count 'lorem ipsum')
[ "${lorem:-0}" -eq 0 ] && ok "no lorem ipsum" || block "$lorem lorem ipsum block(s)"

section "Code hygiene"
todos=$(grep -rn 'TODO\|FIXME\|HACK\|XXX' src 2>/dev/null | wc -l | tr -d ' ')
[ "${todos:-0}" -eq 0 ] && ok "no TODO/FIXME markers" || warn "$todos TODO/FIXME marker(s)"

anys=$(grep -rn ': any\b\|as any' src --exclude-dir=generated 2>/dev/null | wc -l | tr -d ' ')
[ "${anys:-0}" -eq 0 ] && ok "no 'any' escapes in TypeScript" || warn "$anys use(s) of 'any'"

# console.* is fine on the server, noise in the browser.
clientlogs=$(grep -rln '"use client"' src 2>/dev/null | xargs grep -ln 'console\.' 2>/dev/null | wc -l | tr -d ' ')
[ "${clientlogs:-0}" -eq 0 ] && ok "no console output in client components" || warn "$clientlogs client component(s) log to the console"

section "Dead files"
dead=0
while IFS= read -r f; do
  base=$(basename "$f"); base="${base%.*}"
  refs=$(grep -rl "\b${base}\b" src --include='*.ts' --include='*.tsx' 2>/dev/null | grep -v "^${f}$" | wc -l | tr -d ' ')
  if [ "${refs:-0}" -eq 0 ]; then warn "unreferenced: $f"; dead=1; fi
done < <(find src -name '*.ts' -o -name '*.tsx' | grep -v '/app/' | grep -v '/generated/' | grep -v '\.config\.ts$')
[ "$dead" -eq 0 ] && ok "every module is imported somewhere"

section "Secrets"
if git ls-files --error-unmatch .env.local >/dev/null 2>&1; then
  block ".env.local is TRACKED BY GIT — credentials would be published"
else
  ok ".env.local is not tracked"
fi

secrets=$(git ls-files 2>/dev/null | xargs grep -lniE 'SMTP_PASSWORD *= *[^ ]|api[_-]?key *= *["'"'"'][a-z0-9]{16}' 2>/dev/null | grep -v '.env.example' | wc -l | tr -d ' ')
[ "${secrets:-0}" -eq 0 ] && ok "no hard-coded credentials in tracked files" || block "$secrets tracked file(s) may contain a credential"

section "Result"
if [ "$blockers" -eq 0 ]; then
  printf '  %sReady — no blockers.%s Warnings above are judgement calls.\n\n' "$GRN" "$OFF"
  exit 0
fi
printf '  %s%s blocker(s) to fix before launch.%s\n\n' "$RED" "$blockers" "$OFF"
exit 1
